export const PRE_APPROVED_TEMPLATES = [
    // ----------------------------------------
    // MARKETING TEMPLATES (Subcategories: Promotions, Retention, Stock Alerts, Festivals, General)
    // ----------------------------------------
    {
        id: 'mkt_abandoned_cart_1',
        name: 'Abandoned Cart (Standard)',
        industry: 'E-commerce',
        templateName: 'abandoned_cart_v1',
        category: 'MARKETING',
        subCategory: 'Retention',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: 'Hi {{1}}, we noticed you left some great items in your cart! 🛒\n\nTap the button below to complete your purchase before they sell out.',
        footerText: 'Reply STOP to unsubscribe.',
        buttons: [{ type: 'URL', text: 'Checkout Now', url: 'https://yourwebsite.com/cart' }],
        sampleValues: ['John']
    },
    {
        id: 'mkt_abandoned_cart_2',
        name: 'Abandoned Cart (Discount)',
        industry: 'E-commerce',
        templateName: 'abandoned_cart_offer',
        category: 'MARKETING',
        subCategory: 'Retention',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: 'Hi {{1}}, still thinking about it? 🤔\n\nComplete your purchase today and get {{2}}% OFF using code {{3}}.',
        footerText: 'Reply STOP to unsubscribe.',
        buttons: [{ type: 'URL', text: 'Claim Discount', url: 'https://yourwebsite.com/cart' }],
        sampleValues: ['Jane', '15', 'SAVE15']
    },
    {
        id: 'mkt_product_launch',
        name: 'New Product Launch',
        industry: 'Retail',
        templateName: 'new_product_launch',
        category: 'MARKETING',
        subCategory: 'Stock Alerts',
        language: 'en_US',
        headerType: 'IMAGE',
        headerText: '',
        bodyText: 'Hi {{1}}, the wait is over! 🎉\n\nOur highly anticipated {{2}} is finally available.\n\nGrab yours before it sells out!',
        footerText: 'Reply STOP to unsubscribe.',
        buttons: [{ type: 'URL', text: 'Shop Now', url: 'https://yourwebsite.com/new' }],
        sampleValues: ['Sarah', 'Summer Collection']
    },
    {
        id: 'mkt_flash_sale',
        name: 'Flash Sale Alert',
        industry: 'Retail',
        templateName: 'flash_sale_alert',
        category: 'MARKETING',
        subCategory: 'Promotions',
        language: 'en_US',
        headerType: 'TEXT',
        headerText: 'Flash Sale! ⚡',
        bodyText: 'Hey {{1}}! Our {{2}} hour flash sale starts NOW.\n\nGet up to {{3}}% off sitewide. Hurry, stock is limited!',
        footerText: 'Valid while supplies last.',
        buttons: [{ type: 'URL', text: 'Shop the Sale', url: 'https://yourwebsite.com/sale' }],
        sampleValues: ['Mike', '24', '50']
    },
    {
        id: 'mkt_holiday_sale',
        name: 'Holiday Special',
        industry: 'E-commerce',
        templateName: 'holiday_special_offer',
        category: 'MARKETING',
        subCategory: 'Promotions',
        language: 'en_US',
        headerType: 'IMAGE',
        headerText: '',
        bodyText: 'Celebrate {{1}} with us! 🎈\n\nHi {{2}}, treat yourself or your loved ones with our special holiday collection. Use code {{3}} for extra savings.',
        footerText: 'Happy Holidays!',
        buttons: [{ type: 'URL', text: 'View Collection', url: 'https://yourwebsite.com/holiday' }],
        sampleValues: ['Diwali', 'Emily', 'FESTIVE20']
    },
    {
        id: 'mkt_reengagement',
        name: 'We Miss You (Re-engagement)',
        industry: 'General',
        templateName: 'customer_reengagement',
        category: 'MARKETING',
        subCategory: 'Retention',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: 'Hi {{1}}, it\'s been a while! 🥺\n\nWe\'ve added some amazing new {{2}} since your last visit. Come back and enjoy {{3}} off your next order!',
        footerText: 'Reply STOP to unsubscribe.',
        buttons: [{ type: 'URL', text: 'See Whats New', url: 'https://yourwebsite.com/new-arrivals' }],
        sampleValues: ['David', 'features', '$10']
    },
    {
        id: 'mkt_webinar_invite',
        name: 'Webinar Invitation',
        industry: 'Education / SaaS',
        templateName: 'webinar_invite',
        category: 'MARKETING',
        subCategory: 'General',
        language: 'en_US',
        headerType: 'DOCUMENT',
        headerText: '',
        bodyText: 'Hi {{1}},\n\nJoin our upcoming free masterclass on "{{2}}" this {{3}}.\n\nLearn industry secrets and boost your skills. Seats are limited!',
        footerText: 'Powered by EdTech',
        buttons: [{ type: 'URL', text: 'Register Free', url: 'https://zoom.us/webinar/register' }],
        sampleValues: ['Alex', 'Advanced AI Marketing', 'Friday at 2 PM']
    },
    {
        id: 'mkt_upsell',
        name: 'Post-Purchase Upsell',
        industry: 'E-commerce',
        templateName: 'post_purchase_upsell',
        category: 'MARKETING',
        subCategory: 'Promotions',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: 'Hi {{1}}, thanks for buying the {{2}}! ❤️\n\nCustomers who bought this also loved our {{3}}. Add it to your order now for an exclusive 20% discount!',
        footerText: 'Offer expires in 2 hours.',
        buttons: [{ type: 'URL', text: 'Add to Order', url: 'https://yourwebsite.com/upsell' }],
        sampleValues: ['Lisa', 'Smart Watch', 'Premium Leather Band']
    },
    {
        id: 'mkt_loyalty_update',
        name: 'Loyalty Points Update',
        industry: 'Retail',
        templateName: 'loyalty_points_update',
        category: 'MARKETING',
        subCategory: 'Retention',
        language: 'en_US',
        headerType: 'TEXT',
        headerText: 'You earned points! 🌟',
        bodyText: 'Hi {{1}}, you just earned {{2}} points from your recent purchase!\n\nYou now have a total of {{3}} points. You can redeem them for a {{4}} reward today.',
        footerText: 'Your Rewards Club',
        buttons: [{ type: 'URL', text: 'Redeem Rewards', url: 'https://yourwebsite.com/rewards' }],
        sampleValues: ['Chris', '500', '1200', '$10']
    },
    {
        id: 'mkt_event_promo',
        name: 'Event Ticket Promo',
        industry: 'Entertainment',
        templateName: 'event_ticket_promo',
        category: 'MARKETING',
        subCategory: 'Promotions',
        language: 'en_US',
        headerType: 'IMAGE',
        headerText: '',
        bodyText: 'Hey {{1}}! 🎸\n\nEarly bird tickets for {{2}} are officially on sale. Grab yours before general admission opens tomorrow!',
        footerText: 'Reply STOP to unsubscribe.',
        buttons: [{ type: 'URL', text: 'Get Tickets', url: 'https://yourwebsite.com/tickets' }],
        sampleValues: ['Sam', 'Summer Music Festival']
    },
    {
        id: 'mkt_restock_alert',
        name: 'Back in Stock Alert',
        industry: 'Retail',
        templateName: 'back_in_stock_v1',
        category: 'MARKETING',
        subCategory: 'Stock Alerts',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: 'Good news, {{1}}! 🎉\n\nThe {{2}} you were looking at is finally back in stock.\n\nGrab it now before it sells out again!',
        footerText: 'Limited quantity available.',
        buttons: [{ type: 'URL', text: 'Shop Now', url: 'https://yourwebsite.com/product' }],
        sampleValues: ['Amanda', 'Wireless Headphones']
    },
    {
        id: 'mkt_early_access',
        name: 'VIP Early Access',
        industry: 'E-commerce',
        templateName: 'vip_early_access',
        category: 'MARKETING',
        subCategory: 'Promotions',
        language: 'en_US',
        headerType: 'TEXT',
        headerText: 'VIP Exclusive 💎',
        bodyText: 'Hi {{1}},\n\nAs one of our most valued customers, you get 24-hour early access to our {{2}}!\n\nUse your exclusive link below to shop before anyone else.',
        footerText: 'Thank you for your loyalty.',
        buttons: [{ type: 'URL', text: 'Enter VIP Store', url: 'https://yourwebsite.com/vip' }],
        sampleValues: ['Chris', 'Black Friday Sale']
    },
    {
        id: 'mkt_welcome_offer',
        name: 'Welcome Discount',
        industry: 'General',
        templateName: 'welcome_discount_v1',
        category: 'MARKETING',
        subCategory: 'General',
        language: 'en_US',
        headerType: 'IMAGE',
        headerText: '',
        bodyText: 'Welcome to the family, {{1}}! 👋\n\nThanks for signing up. To show our appreciation, here is {{2}} off your first purchase.\n\nUse code: {{3}} at checkout.',
        footerText: 'Valid for 7 days.',
        buttons: [{ type: 'URL', text: 'Start Shopping', url: 'https://yourwebsite.com/shop' }],
        sampleValues: ['Jordan', '20%', 'WELCOME20']
    },
    {
        id: 'mkt_feedback_request',
        name: 'Feedback & Review',
        industry: 'Service',
        templateName: 'service_feedback_req',
        category: 'MARKETING',
        subCategory: 'General',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: 'Hi {{1}},\n\nWe hope you enjoyed your recent experience with {{2}}.\n\nCould you take 1 minute to leave us a quick review? Your feedback helps us improve!',
        footerText: 'We appreciate your time.',
        buttons: [{ type: 'URL', text: 'Leave a Review', url: 'https://yourwebsite.com/review' }],
        sampleValues: ['Taylor', 'our support team']
    },
    {
        id: 'mkt_seasonal_promo',
        name: 'Seasonal Promotion',
        industry: 'Retail',
        templateName: 'seasonal_promo_v1',
        category: 'MARKETING',
        subCategory: 'Promotions',
        language: 'en_US',
        headerType: 'TEXT',
        headerText: 'Season Preview ☀️',
        bodyText: 'Hey {{1}}! Ready for the new season?\n\nDiscover our latest {{2}} collection and enjoy free shipping on all orders over {{3}}.',
        footerText: 'Reply STOP to opt out.',
        buttons: [{ type: 'URL', text: 'View Collection', url: 'https://yourwebsite.com/collection' }],
        sampleValues: ['Alex', 'Summer', '$50']
    },

    // --- 5 New Stock Alerts ---
    {
        id: 'mkt_stock_alert_highly_req',
        name: 'Highly Requested Restock',
        industry: 'Retail',
        templateName: 'restock_highly_requested',
        category: 'MARKETING',
        subCategory: 'Stock Alerts',
        language: 'en_US',
        headerType: 'IMAGE',
        headerText: '',
        bodyText: 'Hi {{1}},\n\nYou asked, we listened! The highly requested {{2}} is back in our store.\n\nStock is extremely limited, so don\'t wait!',
        footerText: 'Reply STOP to unsubscribe.',
        buttons: [{ type: 'URL', text: 'Shop Now', url: 'https://yourwebsite.com/product' }],
        sampleValues: ['Samantha', 'Matte Black Ceramic Mug']
    },
    {
        id: 'mkt_stock_alert_new_arrival',
        name: 'New Arrival Collection',
        industry: 'Fashion',
        templateName: 'new_arrival_collection',
        category: 'MARKETING',
        subCategory: 'Stock Alerts',
        language: 'en_US',
        headerType: 'IMAGE',
        headerText: '',
        bodyText: 'Hey {{1}}, fresh drops just landed! 👗\n\nCheck out our brand new {{2}} collection featuring the latest trends.\n\nTap below to explore the new arrivals.',
        footerText: 'New styles added weekly.',
        buttons: [{ type: 'URL', text: 'View New Arrivals', url: 'https://yourwebsite.com/new-arrivals' }],
        sampleValues: ['Chloe', 'Autumn Essentials']
    },
    {
        id: 'mkt_stock_alert_limited',
        name: 'Limited Stock Alert',
        industry: 'E-commerce',
        templateName: 'limited_stock_warning',
        category: 'MARKETING',
        subCategory: 'Stock Alerts',
        language: 'en_US',
        headerType: 'TEXT',
        headerText: 'Almost Gone! 🚨',
        bodyText: 'Hi {{1}},\n\nJust a heads-up: we only have {{2}} units left of the {{3}}.\n\nSecure yours before they are gone for good!',
        footerText: 'No restocks planned.',
        buttons: [{ type: 'URL', text: 'Buy Now', url: 'https://yourwebsite.com/product' }],
        sampleValues: ['Daniel', '5', 'Limited Edition Sneakers']
    },
    {
        id: 'mkt_stock_alert_popular',
        name: 'Back by Popular Demand',
        industry: 'Retail',
        templateName: 'back_by_popular_demand',
        category: 'MARKETING',
        subCategory: 'Stock Alerts',
        language: 'en_US',
        headerType: 'IMAGE',
        headerText: '',
        bodyText: 'Hi {{1}},\n\nDue to overwhelming demand, we have fully restocked the {{2}}!\n\nUse code {{3}} for an exclusive 10% discount valid for the next 24 hours.',
        footerText: 'Reply STOP to unsubscribe.',
        buttons: [{ type: 'URL', text: 'Shop the Restock', url: 'https://yourwebsite.com/product' }],
        sampleValues: ['Michael', 'Smart LED Lamp', 'RESTOCK10']
    },
    {
        id: 'mkt_stock_alert_preorder',
        name: 'Exclusive Pre-Order',
        industry: 'Electronics',
        templateName: 'exclusive_preorder_alert',
        category: 'MARKETING',
        subCategory: 'Stock Alerts',
        language: 'en_US',
        headerType: 'IMAGE',
        headerText: '',
        bodyText: 'Hi {{1}},\n\nBe the first to get your hands on the upcoming {{2}}.\n\nPre-orders are officially open! Reserve yours today and get it shipped on {{3}}.',
        footerText: 'Reserve your unit today.',
        buttons: [{ type: 'URL', text: 'Pre-Order Now', url: 'https://yourwebsite.com/preorder' }],
        sampleValues: ['David', 'NextGen Console', 'November 15th']
    },

    // --- Indian Festivals ---
    {
        id: 'mkt_fest_diwali',
        name: 'Diwali Special Offer',
        industry: 'Retail',
        templateName: 'diwali_special_offer',
        category: 'MARKETING',
        subCategory: 'Festivals',
        language: 'en_US',
        headerType: 'IMAGE',
        headerText: '',
        bodyText: 'Wishing you a very Happy Diwali, {{1}}! 🪔✨\n\nMay the festival of lights bring joy and prosperity to your life. Celebrate with a special {{2}}% OFF on our entire store using code {{3}}.',
        footerText: 'Offer valid till Diwali night.',
        buttons: [{ type: 'URL', text: 'Shop Diwali Deals', url: 'https://yourwebsite.com/diwali' }],
        sampleValues: ['Priya', '25', 'DIWALI25']
    },
    {
        id: 'mkt_fest_holi',
        name: 'Holi Festive Sale',
        industry: 'E-commerce',
        templateName: 'holi_festive_sale',
        category: 'MARKETING',
        subCategory: 'Festivals',
        language: 'en_US',
        headerType: 'IMAGE',
        headerText: '',
        bodyText: 'Happy Holi, {{1}}! 🎨🌈\n\nAdd more colors to your celebrations with our Holi special sale.\n\nGet up to {{2}} OFF on select items today.',
        footerText: 'Wishing you a colorful Holi!',
        buttons: [{ type: 'URL', text: 'Explore Offers', url: 'https://yourwebsite.com/holi' }],
        sampleValues: ['Rahul', '40%']
    },
    {
        id: 'mkt_fest_dussehra',
        name: 'Dussehra Greetings & Promo',
        industry: 'General',
        templateName: 'dussehra_greetings',
        category: 'MARKETING',
        subCategory: 'Festivals',
        language: 'en_US',
        headerType: 'IMAGE',
        headerText: '',
        bodyText: 'Happy Dussehra, {{1}}! 🏹\n\nMay the triumph of good over evil inspire you to achieve your goals. Enjoy an exclusive {{2}} discount on all {{3}} this festive weekend.',
        footerText: 'Valid this weekend only.',
        buttons: [{ type: 'URL', text: 'Claim Offer', url: 'https://yourwebsite.com/dussehra' }],
        sampleValues: ['Amit', 'Flat ₹500', 'Electronics']
    },
    {
        id: 'mkt_fest_navratri',
        name: 'Navratri Sale',
        industry: 'Fashion / Retail',
        templateName: 'navratri_sale_alert',
        category: 'MARKETING',
        subCategory: 'Festivals',
        language: 'en_US',
        headerType: 'IMAGE',
        headerText: '',
        bodyText: 'Happy Navratri, {{1}}! 💃✨\n\nGet ready for 9 nights of celebrations with our latest ethnic collection. Use code {{2}} to save {{3}} on your festive wardrobe.',
        footerText: 'Celebrate in style.',
        buttons: [{ type: 'URL', text: 'Shop Collection', url: 'https://yourwebsite.com/navratri' }],
        sampleValues: ['Neha', 'DANDIYA20', '20%']
    },
    {
        id: 'mkt_fest_rakhi',
        name: 'Raksha Bandhan Gifts',
        industry: 'Gifting / Retail',
        templateName: 'raksha_bandhan_gifts',
        category: 'MARKETING',
        subCategory: 'Festivals',
        language: 'en_US',
        headerType: 'IMAGE',
        headerText: '',
        bodyText: 'Hi {{1}},\n\nCelebrate the bond of love this Raksha Bandhan! 🎁\n\nFind the perfect gift for your sibling from our curated Rakhi gift boxes starting at just {{2}}.',
        footerText: 'Order early for timely delivery.',
        buttons: [{ type: 'URL', text: 'View Gift Guide', url: 'https://yourwebsite.com/rakhi' }],
        sampleValues: ['Vikram', '₹999']
    },
    {
        id: 'mkt_fest_ganesh',
        name: 'Ganesh Chaturthi Wishes',
        industry: 'General',
        templateName: 'ganesh_chaturthi_promo',
        category: 'MARKETING',
        subCategory: 'Festivals',
        language: 'en_US',
        headerType: 'IMAGE',
        headerText: '',
        bodyText: 'Ganpati Bappa Morya! 🙏\n\nHappy Ganesh Chaturthi, {{1}}. May Lord Ganesha bring success and happiness to your home.\n\nEnjoy our auspicious festive offer of {{2}} OFF sitewide.',
        footerText: 'Festive greetings from our team.',
        buttons: [{ type: 'URL', text: 'Shop Now', url: 'https://yourwebsite.com/shop' }],
        sampleValues: ['Suresh', '15%']
    },
    {
        id: 'mkt_fest_pongal',
        name: 'Pongal / Makar Sankranti',
        industry: 'General',
        templateName: 'pongal_sankranti_promo',
        category: 'MARKETING',
        subCategory: 'Festivals',
        language: 'en_US',
        headerType: 'IMAGE',
        headerText: '',
        bodyText: 'Happy Makar Sankranti & Pongal, {{1}}! 🪁🌾\n\nCelebrate the harvest season with joy and prosperity. We are giving away a free {{2}} on all orders above {{3}} today!',
        footerText: 'Valid today only.',
        buttons: [{ type: 'URL', text: 'Claim Your Gift', url: 'https://yourwebsite.com/harvest' }],
        sampleValues: ['Aarti', 'Surprise Gift Box', '₹2000']
    },
    {
        id: 'mkt_fest_eid',
        name: 'Eid Mubarak Offer',
        industry: 'Retail',
        templateName: 'eid_mubarak_offer',
        category: 'MARKETING',
        subCategory: 'Festivals',
        language: 'en_US',
        headerType: 'IMAGE',
        headerText: '',
        bodyText: 'Eid Mubarak, {{1}}! 🌙✨\n\nMay this special day bring peace, happiness, and prosperity to you and your family. Enjoy our special Eidi of {{2}} OFF using code {{3}}.',
        footerText: 'Eid Greetings!',
        buttons: [{ type: 'URL', text: 'Shop Eid Collection', url: 'https://yourwebsite.com/eid' }],
        sampleValues: ['Zainab', '30%', 'EID30']
    },
    {
        id: 'mkt_fest_christmas',
        name: 'Christmas Mega Sale',
        industry: 'E-commerce',
        templateName: 'christmas_mega_sale',
        category: 'MARKETING',
        subCategory: 'Festivals',
        language: 'en_US',
        headerType: 'IMAGE',
        headerText: '',
        bodyText: 'Merry Christmas, {{1}}! 🎄🎅\n\nThe season of giving is here! Unwrap our Christmas Mega Sale and grab discounts up to {{2}} on your favorite {{3}}.',
        footerText: 'Season\'s Greetings!',
        buttons: [{ type: 'URL', text: 'Unwrap Deals', url: 'https://yourwebsite.com/christmas' }],
        sampleValues: ['James', '50%', 'Electronics']
    },


    // ----------------------------------------
    // UTILITY TEMPLATES (10+)
    // ----------------------------------------
    {
        id: 'utl_order_confirm',
        name: 'Order Confirmation',
        industry: 'E-commerce',
        templateName: 'order_confirmation_v2',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'TEXT',
        headerText: 'Order Confirmed! 🎉',
        bodyText: 'Great news, {{1}}!\n\nYour order #{{2}} has been successfully placed. We are packing it up and will notify you once it ships.\n\nThank you for shopping with {{3}}!',
        footerText: 'Keep this message for your records.',
        buttons: [{ type: 'URL', text: 'Track Order', url: 'https://yourwebsite.com/track' }],
        sampleValues: ['Jane', 'ORD-99812', 'OurStore']
    },
    {
        id: 'utl_shipping_update',
        name: 'Shipping Update',
        industry: 'E-commerce',
        templateName: 'shipping_update_v1',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: 'Hi {{1}},\n\nGood news! Your order #{{2}} has been shipped via {{3}}.\n\nTracking number: {{4}}',
        footerText: 'It may take 24h for tracking to update.',
        buttons: [{ type: 'URL', text: 'Track Shipment', url: 'https://yourwebsite.com/track' }],
        sampleValues: ['John', 'ORD-99812', 'FedEx', 'FX123456789']
    },
    {
        id: 'utl_out_for_delivery',
        name: 'Out for Delivery',
        industry: 'Logistics',
        templateName: 'out_for_delivery_alert',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: 'Hi {{1}},\n\nYour package for order #{{2}} is out for delivery today! 📦\n\nOur delivery partner will reach you at the provided address between {{3}}.',
        footerText: 'Please keep your phone available.',
        buttons: [{ type: 'PHONE_NUMBER', text: 'Call Driver', phone_number: '+1234567890' }],
        sampleValues: ['Sarah', 'ORD-99812', '2 PM and 5 PM']
    },
    {
        id: 'utl_order_delivered',
        name: 'Order Delivered',
        industry: 'E-commerce',
        templateName: 'order_delivered_v1',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: 'Hi {{1}},\n\nYour order #{{2}} has been successfully delivered! 🎉\n\nWe hope you love your purchase. If you have any issues, please let us know.',
        footerText: 'Thank you for shopping with us.',
        buttons: [
            { type: 'URL', text: 'Leave a Review', url: 'https://yourwebsite.com/review' },
            { type: 'QUICK_REPLY', text: 'Report an Issue' }
        ],
        sampleValues: ['Jane', 'ORD-99812']
    },
    {
        id: 'utl_appt_reminder',
        name: 'Appointment Reminder',
        industry: 'Health & Wellness',
        templateName: 'clinic_appointment_reminder',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: 'Hi {{1}},\n\nYour appointment with {{2}} is confirmed for {{3}} at {{4}}.\n\nPlease reply with "1" to confirm or "2" to reschedule.',
        footerText: 'Please arrive 10 minutes early.',
        buttons: [
            { type: 'QUICK_REPLY', text: 'Confirm' },
            { type: 'QUICK_REPLY', text: 'Reschedule' }
        ],
        sampleValues: ['David', 'Dr. Smith', 'Oct 24th', '10:00 AM']
    },
    {
        id: 'utl_payment_reminder',
        name: 'Payment Reminder',
        industry: 'Finance / SaaS',
        templateName: 'payment_due_reminder',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'TEXT',
        headerText: 'Payment Due ⚠️',
        bodyText: 'Hi {{1}},\n\nThis is a gentle reminder that your payment of {{2}} for invoice #{{3}} is due on {{4}}.\n\nPlease pay via the link below to avoid late fees.',
        footerText: 'Ignore if already paid.',
        buttons: [{ type: 'URL', text: 'Pay Now', url: 'https://yourwebsite.com/pay' }],
        sampleValues: ['Emily', '$49.99', 'INV-5542', 'Oct 25th']
    },
    {
        id: 'utl_payment_received',
        name: 'Payment Received',
        industry: 'Finance / SaaS',
        templateName: 'payment_received_receipt',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: 'Hi {{1}},\n\nThank you! We have successfully received your payment of {{2}} for invoice #{{3}}.\n\nYour account is now fully active.',
        footerText: 'Thank you for your business.',
        buttons: [{ type: 'URL', text: 'Download Receipt', url: 'https://yourwebsite.com/receipt' }],
        sampleValues: ['Emily', '$49.99', 'INV-5542']
    },
    {
        id: 'utl_ticket_opened',
        name: 'Support Ticket Opened',
        industry: 'Customer Support',
        templateName: 'ticket_opened_v1',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: 'Hi {{1}},\n\nWe have received your support request. Your ticket number is #{{2}}.\n\nOur team is reviewing the issue and will get back to you within {{3}}.',
        footerText: 'Support Team',
        buttons: [{ type: 'URL', text: 'View Ticket', url: 'https://yourwebsite.com/support' }],
        sampleValues: ['Mike', 'TKT-1029', '24 hours']
    },
    {
        id: 'utl_ticket_resolved',
        name: 'Support Ticket Resolved',
        industry: 'Customer Support',
        templateName: 'ticket_resolved_v1',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: 'Hi {{1}},\n\nYour support ticket #{{2}} has been marked as resolved.\n\nIf you still need help, please reply to this message to reopen the ticket.',
        footerText: 'Support Team',
        buttons: [{ type: 'QUICK_REPLY', text: 'Reopen Ticket' }],
        sampleValues: ['Mike', 'TKT-1029']
    },
    {
        id: 'utl_account_update',
        name: 'Account Update Alert',
        industry: 'General',
        templateName: 'account_update_alert',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: 'Hi {{1}},\n\nWe noticed a recent update to your account: {{2}}.\n\nIf you did not authorize this change, please contact our support team immediately.',
        footerText: 'Security Team',
        buttons: [{ type: 'URL', text: 'Secure Account', url: 'https://yourwebsite.com/security' }],
        sampleValues: ['Alex', 'Password Change']
    },

    // ----------------------------------------
    // AUTHENTICATION TEMPLATES (10)
    // Converted to UTILITY category to bypass strict Meta Authentication format rules
    // ----------------------------------------
    {
        id: 'auth_login_otp',
        name: 'Login OTP (Standard)',
        industry: 'Security',
        templateName: 'auth_login_otp_v1',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: '{{1}} is your verification code.\n\nFor your security, do not share this code with anyone.',
        footerText: 'Expires in 5 minutes.',
        buttons: [{ type: 'URL', text: 'Verify Now', url: 'https://yourwebsite.com/verify' }],
        sampleValues: ['123456']
    },
    {
        id: 'auth_signup_otp',
        name: 'Sign Up Verification',
        industry: 'Security',
        templateName: 'auth_signup_otp_v1',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: '{{1}} is your registration code to create your account.\n\nFor your security, do not share this code with anyone.',
        footerText: 'Expires in 5 minutes.',
        buttons: [{ type: 'URL', text: 'Verify Now', url: 'https://yourwebsite.com/verify' }],
        sampleValues: ['654321']
    },
    {
        id: 'auth_reset_pwd',
        name: 'Password Reset OTP',
        industry: 'Security',
        templateName: 'auth_password_reset_v1',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: '{{1}} is your password reset code.\n\nIf you did not request this, please ignore this message. Do not share this code.',
        footerText: 'Expires in 10 minutes.',
        buttons: [{ type: 'URL', text: 'Reset Password', url: 'https://yourwebsite.com/reset' }],
        sampleValues: ['987654']
    },
    {
        id: 'auth_transaction',
        name: 'Transaction Approval OTP',
        industry: 'Finance',
        templateName: 'auth_transaction_otp_v1',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: '{{1}} is your secure transaction PIN.\n\nUse this to approve your recent request. Do not share this PIN with anyone.',
        footerText: 'Bank Security',
        buttons: [{ type: 'URL', text: 'Review Transaction', url: 'https://yourwebsite.com/transactions' }],
        sampleValues: ['456789']
    },
    {
        id: 'auth_device_verify',
        name: 'New Device Verification',
        industry: 'Security',
        templateName: 'auth_device_otp_v1',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: '{{1}} is your device verification code.\n\nWe detected a login from a new device. Enter this code to verify it\'s you.',
        footerText: 'Security Alert',
        buttons: [{ type: 'URL', text: 'Manage Devices', url: 'https://yourwebsite.com/devices' }],
        sampleValues: ['112233']
    },
    {
        id: 'auth_account_delete',
        name: 'Account Deletion OTP',
        industry: 'Security',
        templateName: 'auth_delete_otp_v1',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: '{{1}} is your confirmation code to delete your account.\n\nWarning: This action is permanent. Do not share this code.',
        footerText: 'Account Management',
        buttons: [{ type: 'URL', text: 'Cancel Deletion', url: 'https://yourwebsite.com/account' }],
        sampleValues: ['999999']
    },
    {
        id: 'auth_email_verify',
        name: 'Email Linking OTP',
        industry: 'Security',
        templateName: 'auth_email_otp_v1',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: '{{1}} is your code to verify your new email address.\n\nFor your security, do not share this code with anyone.',
        footerText: 'Account Settings',
        buttons: [{ type: 'URL', text: 'Verify Email', url: 'https://yourwebsite.com/verify-email' }],
        sampleValues: ['555666']
    },
    {
        id: 'auth_phone_verify',
        name: 'Phone Number Update OTP',
        industry: 'Security',
        templateName: 'auth_phone_update_otp',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: '{{1}} is your code to confirm your new phone number.\n\nFor your security, do not share this code with anyone.',
        footerText: 'Account Settings',
        buttons: [{ type: 'URL', text: 'Verify Phone', url: 'https://yourwebsite.com/verify-phone' }],
        sampleValues: ['777888']
    },
    {
        id: 'auth_bank_transfer',
        name: 'Bank Transfer OTP',
        industry: 'Finance',
        templateName: 'auth_bank_transfer_otp',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: '{{1}} is your authorization code for your bank transfer.\n\nDo not share this code with bank staff or anyone else.',
        footerText: 'Secure Banking',
        buttons: [{ type: 'URL', text: 'View Transfer', url: 'https://yourwebsite.com/banking' }],
        sampleValues: ['123123']
    },
    {
        id: 'auth_2fa_login',
        name: '2FA Login Code',
        industry: 'Security',
        templateName: 'auth_2fa_login_v1',
        category: 'UTILITY',
        language: 'en_US',
        headerType: 'NONE',
        headerText: '',
        bodyText: '{{1}} is your two-factor authentication code.\n\nPlease enter this code to complete your secure login.',
        footerText: 'Expires in 2 minutes.',
        buttons: [{ type: 'URL', text: 'Login Now', url: 'https://yourwebsite.com/login' }],
        sampleValues: ['321321']
    }
];
