version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatshub-backend
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - PORT=3001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_TLS=false
      - WEBHOOK_VERIFY_TOKEN=${WEBHOOK_VERIFY_TOKEN}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - META_API_VERSION=${META_API_VERSION}
      - META_APP_ID=${META_APP_ID}
      - META_APP_SECRET=${META_APP_SECRET}
      - META_CONFIG_ID=${META_CONFIG_ID}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_STORAGE_BUCKET=${SUPABASE_STORAGE_BUCKET}
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    container_name: whatshub-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
